export const addresses: string[] = [
  "Nablus",
  "Ramallah",
  "Al-Bireh",
  "Jerusalem",
  "Jenin",
  "Tulkarm",
  "Qalqilya",
  "Hebron",
  "Salfit",
  "Tubas",
  "Bethlehem",
  "Jericho",
  "Beit Jala",
  "Beit Sahour",
  "Abu Dis",
  "The occupied interior- 48 cities",
  "Gaza",
  "Other",
];
